import { describe, expect, it } from 'vitest';
import { computeDayDerived, computeMonthlyTotals } from './attendanceCalc';
import type { AttendanceColumnRow, AttendanceDayDerived } from './types';

/**
 * ここでのテストケースは、gas-childcare-visit-app/AttendanceCalc.js(GAS版・給与計算に
 * 直結する実運用コード)をNode上でそのまま実行した結果を「正解」として、TypeScript移植版
 * (attendanceCalc.ts)の出力と1件ずつ突き合わせて確認済みのもの(CLAUDE.mdの
 * 「Logic verification」に基づく検証手法。実際の出勤簿データが無いため、所定内/所定外の
 * 境界・mtg特例・積雪補正・基準距離超過の5km刻み・訪問回数判定・不正な時刻文字列など、
 * 計算式の分岐を網羅する合成データで検証した)。給与計算に直結するため、この一致は
 * 一時的なものではなく、計算式を変更する際は必ずこの回帰テストが通ることを確認すること。
 */
interface Case {
  label: string;
  rowData: AttendanceColumnRow;
  expected: AttendanceDayDerived;
}

const CASES: Case[] = [
  {
    label: '基本: 訪問1件のみ、所定内',
    rowData: { D: '10:00', E: '12:00' },
    expected: {
      leg1MoveStart: '12:00',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 120,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: '訪問3件+事務2件、移動あり、天候なし',
    rowData: {
      D: '09:00',
      E: '10:00',
      H: '30',
      I: '',
      M: '10:45',
      N: '12:00',
      Q: '20',
      R: '',
      V: '12:35',
      W: '14:00',
      X: '事務作業A',
      Y: '14:30',
      Z: '15:30',
      AA: '事務作業B',
      AB: '15:45',
      AC: '16:30',
      AG: '5.5',
      AH: '3.2',
      AI: '10',
      AJ: '8',
    },
    expected: {
      leg1MoveStart: '10:00',
      leg1MoveEnd: '10:30',
      leg1WeatherAdjustedMoveMin: 30,
      leg1WaitMin: 15,
      leg2MoveStart: '12:00',
      leg2MoveEnd: '12:20',
      leg2WeatherAdjustedMoveMin: 20,
      leg2WaitMin: 15,
      laborMinutes: 265,
      overtimeMinutes: 60,
      totalMoveMin: 50,
      totalDistanceKm: 26.7,
      overThresholdCount: 0,
      visitCount: 3,
    },
  },
  {
    label: '積雪あり: 移動時間が1.3倍になる',
    rowData: { E: '10:00', H: '20', I: '雪', M: '10:30' },
    expected: {
      leg1MoveStart: '10:00',
      leg1MoveEnd: '10:20',
      leg1WeatherAdjustedMoveMin: 26,
      leg1WaitMin: 10,
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 26,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: '積雪あり(小数点以下の丸め確認): 移動33分',
    rowData: { E: '09:00', H: '33', I: '雪', M: '10:00' },
    expected: {
      leg1MoveStart: '09:00',
      leg1MoveEnd: '09:33',
      leg1WeatherAdjustedMoveMin: 42.9,
      leg1WaitMin: 27,
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 42.9,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: 'mtg特例: ラベルが大文字混在(MTG)でも所定内扱い',
    rowData: { X: 'MTG会議', Y: '18:00', Z: '20:00' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 120,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: 'mtg特例なし: 所定外時間帯はそのまま残業扱い',
    rowData: { AA: '備品購入', AB: '18:00', AC: '20:00' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 120,
      totalMoveMin: 0,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: '距離超過ちょうど15km(境界値、超過なし)',
    rowData: { AG: '15', AH: '0', AI: '0', AJ: '0' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 15,
      overThresholdCount: 0,
      visitCount: 3,
    },
  },
  {
    label: '距離超過16km(1回分超過)',
    rowData: { AG: '16', AH: '0', AI: '0', AJ: '0' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 16,
      overThresholdCount: 0,
      visitCount: 3,
    },
  },
  {
    label: '距離超過35km(4回分超過、5km刻み)',
    rowData: { AG: '35', AH: '0', AI: '0', AJ: '0' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 35,
      overThresholdCount: 4,
      visitCount: 3,
    },
  },
  {
    label: '複数列で超過が発生する場合は列ごとに計算して合算する(AG=20→1回、AH=25→2回)',
    rowData: { AG: '20', AH: '25', AI: '0', AJ: '0' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 45,
      overThresholdCount: 3,
      visitCount: 3,
    },
  },
  {
    label: '訪問回数判定: AH(#2移動距離)が数値なら3',
    rowData: { AG: '5', AH: '3', AI: '1', AJ: '1' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 10,
      overThresholdCount: 0,
      visitCount: 3,
    },
  },
  {
    label: '訪問回数判定: AGのみ数値なら2',
    rowData: { AG: '5', AI: '1', AJ: '1' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 7,
      overThresholdCount: 0,
      visitCount: 2,
    },
  },
  {
    label: '訪問回数判定: AI/AJのみ数値なら1',
    rowData: { AI: '1' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 1,
      overThresholdCount: 0,
      visitCount: 1,
    },
  },
  {
    label: '訪問回数判定: 全て未入力なら0',
    rowData: {},
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: '終業<=始業(逆転した時間帯)は所定内0扱い',
    rowData: { D: '12:00', E: '10:00' },
    expected: {
      leg1MoveStart: '10:00',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    // parseTimeToMinutesは "\d{1,2}:\d{2}" という形式だけを見ており、時刻として妥当な範囲かは
    // 検証しない(GAS版の実際の挙動)。"25:99" は 25*60+99=1599分として計算され、
    // formatMinutesToTimeの24時間モジュロで "02:39" という一見もっともらしいが誤った時刻になる。
    // これはGAS版の既知の挙動であり、この移植ではあえてそのまま踏襲している。
    label: '不正な時刻文字列(範囲外)は形式チェックだけ通り、24時間モジュロで丸められる',
    rowData: { D: 'invalid', E: '25:99' },
    expected: {
      leg1MoveStart: '02:39',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: '日をまたぐ移動(23:50→翌00:10)のフォーマット丸め確認',
    rowData: { E: '23:50', H: '20', M: '00:10' },
    expected: {
      leg1MoveStart: '23:50',
      leg1MoveEnd: '00:10',
      leg1WeatherAdjustedMoveMin: 20,
      leg1WaitMin: 0,
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 20,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: '空文字列の距離は超過カウントの対象外',
    rowData: { AG: '' },
    expected: {
      leg1MoveStart: '',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 0,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
  {
    label: '買物代行(AN)は日次derivedには含まれない(月合計でのみ集計)',
    rowData: { D: '10:00', E: '11:00', AN: '2' },
    expected: {
      leg1MoveStart: '11:00',
      leg1MoveEnd: '',
      leg1WeatherAdjustedMoveMin: '',
      leg1WaitMin: '',
      leg2MoveStart: '',
      leg2MoveEnd: '',
      leg2WeatherAdjustedMoveMin: '',
      leg2WaitMin: '',
      laborMinutes: 60,
      overtimeMinutes: 0,
      totalMoveMin: 0,
      totalDistanceKm: 0,
      overThresholdCount: 0,
      visitCount: 0,
    },
  },
];

describe('computeDayDerived (GAS版AttendanceCalc.jsとの数値一致を検証済み)', () => {
  it.each(CASES.map((c) => [c.label, c.rowData, c.expected] as const))('%s', (_label, rowData, expected) => {
    expect(computeDayDerived(rowData)).toEqual(expected);
  });
});

describe('computeMonthlyTotals (GAS版との数値一致を検証済み)', () => {
  it('上記全ケースを1か月分として集計した場合の合計値がGAS版と一致する', () => {
    const days = CASES.map((c) => ({ rowData: c.rowData, derived: computeDayDerived(c.rowData) }));
    expect(computeMonthlyTotals(days)).toEqual({
      laborMinutes: 565,
      overtimeMinutes: 180,
      totalMoveMin: 138.9,
      leg1DistanceKmTotal: 101.5,
      leg2DistanceKmTotal: 31.2,
      attendanceDistanceKmTotal: 13,
      leavingDistanceKmTotal: 10,
      totalDistanceKm: 155.7,
      overThresholdCount: 7,
      visitCountTotal: 21,
      shoppingErrandTotal: 2,
    });
  });
});
