DROP INDEX "receipts_tenant_dedupe_blind_index_idx";--> statement-breakpoint
ALTER TABLE "accident_reports" DROP COLUMN "content_ciphertext";--> statement-breakpoint
ALTER TABLE "accident_reports" DROP COLUMN "content_key_version";--> statement-breakpoint
ALTER TABLE "attendance_days" DROP COLUMN "row_data_ciphertext";--> statement-breakpoint
ALTER TABLE "attendance_days" DROP COLUMN "row_data_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "emergency_contact_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "emergency_contact_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "emergency_contact_relation_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "emergency_contact_relation_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "evacuation_site_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "evacuation_site_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "memo_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "memo_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "benefit_member_id_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "benefit_member_id_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "lat_lng_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "lat_lng_key_version";--> statement-breakpoint
ALTER TABLE "daily_reports" DROP COLUMN "content_ciphertext";--> statement-breakpoint
ALTER TABLE "daily_reports" DROP COLUMN "content_key_version";--> statement-breakpoint
ALTER TABLE "family_members" DROP COLUMN "name_ciphertext";--> statement-breakpoint
ALTER TABLE "family_members" DROP COLUMN "name_key_version";--> statement-breakpoint
ALTER TABLE "family_members" DROP COLUMN "dob_ciphertext";--> statement-breakpoint
ALTER TABLE "family_members" DROP COLUMN "dob_key_version";--> statement-breakpoint
ALTER TABLE "family_members" DROP COLUMN "info_ciphertext";--> statement-breakpoint
ALTER TABLE "family_members" DROP COLUMN "info_key_version";--> statement-breakpoint
ALTER TABLE "receipts" DROP COLUMN "dedupe_blind_index";--> statement-breakpoint
ALTER TABLE "receipts" DROP COLUMN "amount_ciphertext";--> statement-breakpoint
ALTER TABLE "receipts" DROP COLUMN "amount_key_version";--> statement-breakpoint
ALTER TABLE "receipts" DROP COLUMN "store_name_ciphertext";--> statement-breakpoint
ALTER TABLE "receipts" DROP COLUMN "store_name_key_version";--> statement-breakpoint
ALTER TABLE "receipts" DROP COLUMN "handoff_text_ciphertext";--> statement-breakpoint
ALTER TABLE "receipts" DROP COLUMN "handoff_text_key_version";