DROP INDEX "staff_tenant_email_blind_idx";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "name_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "name_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "family_name_blind_index";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "given_name_blind_index";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "family_name_kana_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "family_name_kana_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "given_name_kana_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "given_name_kana_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "email_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "email_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "email_blind_index";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "phone_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "phone_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "phone_blind_index";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "address_detail_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "address_detail_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "city_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "city_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "city_blind_index";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "parking_area_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "parking_area_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "parking_detail_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "parking_detail_key_version";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "address2_ciphertext";--> statement-breakpoint
ALTER TABLE "customers" DROP COLUMN "address2_key_version";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "name_ciphertext";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "name_key_version";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "family_name_blind_index";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "given_name_blind_index";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "email_ciphertext";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "email_key_version";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "email_blind_index";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "phone_ciphertext";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "phone_key_version";--> statement-breakpoint
ALTER TABLE "staff" DROP COLUMN "phone_blind_index";